//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2015-02-09 23:15:26 
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using DP.Data.OracleClient.Mapping;
using DP.Data.SqlClient.Mapping;
using DP.Data.Common;
using System.Configuration;
namespace VoiceMail.Entity
{
	
	/// <summary>
	/// 留言表
	/// </summary>	
	[Serializable]
	[OracleTable(TableName = "MsgBox" , TableOrView = DP.Data.Common.TableType.Table, ConnectionStringKey = "SQLConnString_VoiceMail")]
    [SqlTable(TableName = "MsgBox" , TableOrView = DP.Data.Common.TableType.Table, ConnectionStringKey = "SQLConnString_VoiceMail")]
	public class MsgBoxEntity 
	{
				/// <summary>
		/// 记录ID
		/// </summary>		
				[OracleColumn(IsDbGenerated = true , IsPrimaryKey = true, ColumnDescription = "记录ID", ColumnName = "RecID")]
        [SqlColumn(IsDbGenerated = true , IsPrimaryKey = true, ColumnDescription = "记录ID", ColumnName = "RecID")]
				public long RecID { get; set; }

				/// <summary>
		/// 预留字段
		/// </summary>		
				[OracleColumn(ColumnDescription = "预留字段", ColumnName = "ActionType")]
        [SqlColumn(ColumnDescription = "预留字段", ColumnName = "ActionType")]		 
				public bool ActionType { get; set; }

				/// <summary>
		/// 主叫号码
		/// </summary>		
				[OracleColumn(ColumnDescription = "主叫号码", ColumnName = "Ani")]
        [SqlColumn(ColumnDescription = "主叫号码", ColumnName = "Ani")]		 
				public string Ani { get; set; }

				/// <summary>
		/// 留言相对路径
		/// </summary>		
				[OracleColumn(ColumnDescription = "留言相对路径", ColumnName = "Content")]
        [SqlColumn(ColumnDescription = "留言相对路径", ColumnName = "Content")]		 
				public string Content { get; set; }

				/// <summary>
		/// 留言时间
		/// </summary>		
				[OracleColumn(ColumnDescription = "留言时间", ColumnName = "ActionTime")]
        [SqlColumn(ColumnDescription = "留言时间", ColumnName = "ActionTime")]		 
				public DateTime? ActionTime { get; set; }

				/// <summary>
		/// 最后听取时间
		/// </summary>		
				[OracleColumn(ColumnDescription = "最后听取时间", ColumnName = "LastReadTime")]
        [SqlColumn(ColumnDescription = "最后听取时间", ColumnName = "LastReadTime")]		 
				public DateTime? LastReadTime { get; set; }

				/// <summary>
		/// 最后听取操作员
		/// </summary>		
				[OracleColumn(ColumnDescription = "最后听取操作员", ColumnName = "LastReadPeople")]
        [SqlColumn(ColumnDescription = "最后听取操作员", ColumnName = "LastReadPeople")]		 
				public string LastReadPeople { get; set; }

				/// <summary>
		/// 预留字段
		/// </summary>		
				[OracleColumn(ColumnDescription = "预留字段", ColumnName = "IsCallBack")]
        [SqlColumn(ColumnDescription = "预留字段", ColumnName = "IsCallBack")]		 
				public int? IsCallBack { get; set; }

				/// <summary>
		/// 留言处理状态
		/// </summary>		
				[OracleColumn(ColumnDescription = "留言处理状态", ColumnName = "Status")]
        [SqlColumn(ColumnDescription = "留言处理状态", ColumnName = "Status")]		 
				public int Status { get; set; }

				/// <summary>
		/// 组编号
		/// </summary>		
				[OracleColumn(ColumnDescription = "组编号", ColumnName = "GroupId")]
        [SqlColumn(ColumnDescription = "组编号", ColumnName = "GroupId")]		 
				public long? GroupId { get; set; }

				/// <summary>
		/// 组名称
		/// </summary>		
				[OracleColumn(ColumnDescription = "组名称", ColumnName = "GroupName")]
        [SqlColumn(ColumnDescription = "组名称", ColumnName = "GroupName")]		 
				public string GroupName { get; set; }

				/// <summary>
		/// 操作员编号
		/// </summary>		
				[OracleColumn(ColumnDescription = "操作员编号", ColumnName = "UserId")]
        [SqlColumn(ColumnDescription = "操作员编号", ColumnName = "UserId")]		 
				public long? UserId { get; set; }

				/// <summary>
		/// 操作员姓名
		/// </summary>		
				[OracleColumn(ColumnDescription = "操作员姓名", ColumnName = "UserName")]
        [SqlColumn(ColumnDescription = "操作员姓名", ColumnName = "UserName")]		 
				public string UserName { get; set; }

				/// <summary>
		/// 服务器地址
		/// </summary>		
				[OracleColumn(ColumnDescription = "服务器地址", ColumnName = "ServerName")]
        [SqlColumn(ColumnDescription = "服务器地址", ColumnName = "ServerName")]		 
				public string ServerName { get; set; }

				/// <summary>
		/// 被叫号码
		/// </summary>		
				[OracleColumn(ColumnDescription = "被叫号码", ColumnName = "Dnis")]
        [SqlColumn(ColumnDescription = "被叫号码", ColumnName = "Dnis")]		 
				public string Dnis { get; set; }

				/// <summary>
		/// 留言时间
		/// </summary>		
				[OracleColumn(ColumnDescription = "留言时间", ColumnName = "RecLenght")]
        [SqlColumn(ColumnDescription = "留言时间", ColumnName = "RecLenght")]		 
				public DateTime? RecLenght { get; set; }

				/// <summary>
		/// 是否有效
		/// </summary>		
				[OracleColumn(ColumnDescription = "是否有效", ColumnName = "IsValid")]
        [SqlColumn(ColumnDescription = "是否有效", ColumnName = "IsValid")]		 
				public int? IsValid { get; set; }

				/// <summary>
		/// 处理记录
		/// </summary>		
				[OracleColumn(ColumnDescription = "处理记录", ColumnName = "HandingRecord")]
        [SqlColumn(ColumnDescription = "处理记录", ColumnName = "HandingRecord")]		 
				public string HandingRecord { get; set; }

				/// <summary>
		/// 备注
		/// </summary>		
				[OracleColumn(ColumnDescription = "备注", ColumnName = "Remark")]
        [SqlColumn(ColumnDescription = "备注", ColumnName = "Remark")]		 
				public string Remark { get; set; }

				/// <summary>
		/// 
		/// </summary>		
				[OracleColumn(ColumnDescription = "", ColumnName = "MsgSubGroup")]
        [SqlColumn(ColumnDescription = "", ColumnName = "MsgSubGroup")]		 
				public string MsgSubGroup { get; set; }

				/// <summary>
		/// 
		/// </summary>		
				[OracleColumn(ColumnDescription = "", ColumnName = "ProcessLenM")]
        [SqlColumn(ColumnDescription = "", ColumnName = "ProcessLenM")]		 
				public long? ProcessLenM { get; set; }

		 

	}
}
