//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2015-02-09 23:15:26 
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using DP.Data.OracleClient.Mapping;
using DP.Data.SqlClient.Mapping;
using DP.Data.Common;
using System.Configuration;
namespace VoiceMail.Entity
{
	
	/// <summary>
	/// 用户表
	/// </summary>	
	[Serializable]
	[OracleTable(TableName = "User" , TableOrView = DP.Data.Common.TableType.Table, ConnectionStringKey = "SQLConnString_VoiceMail")]
    [SqlTable(TableName = "User" , TableOrView = DP.Data.Common.TableType.Table, ConnectionStringKey = "SQLConnString_VoiceMail")]
	public class UserEntity 
	{
				/// <summary>
		/// 操作员编号
		/// </summary>		
				[OracleColumn(IsDbGenerated = true , IsPrimaryKey = true, ColumnDescription = "操作员编号", ColumnName = "UserId")]
        [SqlColumn(IsDbGenerated = true , IsPrimaryKey = true, ColumnDescription = "操作员编号", ColumnName = "UserId")]
				public long UserId { get; set; }

				/// <summary>
		/// 登录名
		/// </summary>		
				[OracleColumn(ColumnDescription = "登录名", ColumnName = "LoginName")]
        [SqlColumn(ColumnDescription = "登录名", ColumnName = "LoginName")]		 
				public string LoginName { get; set; }

				/// <summary>
		/// 密码
		/// </summary>		
				[OracleColumn(ColumnDescription = "密码", ColumnName = "Password")]
        [SqlColumn(ColumnDescription = "密码", ColumnName = "Password")]		 
				public string Password { get; set; }

				/// <summary>
		/// 操作员姓名
		/// </summary>		
				[OracleColumn(ColumnDescription = "操作员姓名", ColumnName = "UserName")]
        [SqlColumn(ColumnDescription = "操作员姓名", ColumnName = "UserName")]		 
				public string UserName { get; set; }

				/// <summary>
		/// 组名称
		/// </summary>		
				[OracleColumn(ColumnDescription = "组名称", ColumnName = "GroupId")]
        [SqlColumn(ColumnDescription = "组名称", ColumnName = "GroupId")]		 
				public long GroupId { get; set; }

				/// <summary>
		/// 备注
		/// </summary>		
				[OracleColumn(ColumnDescription = "备注", ColumnName = "Remark")]
        [SqlColumn(ColumnDescription = "备注", ColumnName = "Remark")]		 
				public string Remark { get; set; }

				/// <summary>
		/// 用户权限等级
		/// </summary>		
				[OracleColumn(ColumnDescription = "用户权限等级", ColumnName = "UserLevel")]
        [SqlColumn(ColumnDescription = "用户权限等级", ColumnName = "UserLevel")]		 
				public int? UserLevel { get; set; }

				/// <summary>
		/// 最后更新时间
		/// </summary>		
				[OracleColumn(ColumnDescription = "最后更新时间", ColumnName = "LastUpdateTime")]
        [SqlColumn(ColumnDescription = "最后更新时间", ColumnName = "LastUpdateTime")]		 
				public DateTime? LastUpdateTime { get; set; }

				/// <summary>
		/// 最后更新人
		/// </summary>		
				[OracleColumn(ColumnDescription = "最后更新人", ColumnName = "LastUpdateUser")]
        [SqlColumn(ColumnDescription = "最后更新人", ColumnName = "LastUpdateUser")]		 
				public string LastUpdateUser { get; set; }

				/// <summary>
		/// 用户状态
		/// </summary>		
				[OracleColumn(ColumnDescription = "用户状态", ColumnName = "UserStatus")]
        [SqlColumn(ColumnDescription = "用户状态", ColumnName = "UserStatus")]		 
				public int UserStatus { get; set; }

				/// <summary>
		/// 
		/// </summary>		
				[OracleColumn(ColumnDescription = "", ColumnName = "GroupName")]
        [SqlColumn(ColumnDescription = "", ColumnName = "GroupName")]		 
				public string GroupName { get; set; }

				/// <summary>
		/// 
		/// </summary>		
				[OracleColumn(ColumnDescription = "", ColumnName = "EMail")]
        [SqlColumn(ColumnDescription = "", ColumnName = "EMail")]		 
				public string EMail { get; set; }

		 

	}
}
